rpg/config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :chapters
  resources :loots
  resources :game_players
  resources :players
  resources :gms
  get '/', to: "home#index"
  get '/home/gm', to: "home#loggm"
  get '/home/player', to: "home#logplayer"

  resources :messages
  resources :games
  resources :channels
  resources :home
  root "home#index"
  post '/home/logingm', to: "home#logingm"
  post '/home/loginplayer', to: "home#loginplayer"
  post '/home/disconnect', to: "home#disconnect"

  resources :choices do
    resources :answers
  end
  resources :steps
  resources :creatures
  get '/games', to: "games#index"
  post '/games/firstjoin/:game_id', to: "games#playerJoinGame"
  get '/games/viewAll/:entity/:id', to: "games#getMyGames"

  get '/games/character/new/:game_id', to: "characters#new"
  post '/games/character/new/:game_id', to: "characters#create"

  post '/game_players/leave/:game_id', to: "game_players#playerLeaveGame"

  get '/games/character/:character_id/setAttribute', to: "attributes#setAttributes"
  patch '/games/character/:character_id/saveAttributes', to: "attributes#saveAttributes"

  get '/games/:game_id/character/:character_id/:current_step', to: "games#playGame"

  get '/games/:game_id/character/:character_id/:current_step/loot/:loot_id', to: "games#earnLoot"

  get '/games/:game_id/character/:character_id/:current_step/wear/:loot_id', to: "games#addEquipment"

  get '/games/:game_id/character/:character_id/:current_step/fight/turn/:turn', to: "games#fight"

  patch '/games/:game_id/character/:character_id/:current_step', to: "attributes#saveAttributesXp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

rpg/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
end

rpg/app/models/channel.rb
class Channel < ApplicationRecord
    has_one :game
end

rpg/app/models/chapter.rb
class Chapter < ApplicationRecord
    has_many :steps, dependent: :destroy

end

rpg/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

rpg/app/models/choice.rb
class Choice < ApplicationRecord
    has_many :answers, dependent: :destroy

    validates :step_id, presence: true
    validates :description, presence: true, length: { minimum: 10 }

end

rpg/app/models/creature.rb
class Creature < ApplicationRecord
    validates :loot_id, presence: true
    validates :strength, presence: true
    validates :life, presence: true
    validates :image, presence: false
    validates :given_exp, presence: true
    

end

rpg/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :channel,
             :class_name => "Channel",
             :foreign_key => 'channel_id'
  has_many :messages, dependent: :destroy
  has_many :players
  has_many :game_players, dependent: :destroy
  has_many :characters, dependent: :destroy
  belongs_to :gm,
             dependent: :destroy,
             :class_name => "Gm",
             :foreign_key => 'gm_id'

 validates :name, presence: true
 validates :description, presence: true, length: { minimum: 10 }
 validates :chapter_id, presence: true
end

rpg/app/models/game_player.rb
class GamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

rpg/app/models/gm.rb
class Gm < ApplicationRecord
    has_one :game
end

rpg/app/models/image.rb
class Image < ApplicationRecord
end

rpg/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :player
  belongs_to :character
  belongs_to :game
end

rpg/app/models/loot.rb
class Loot < ApplicationRecord
end

rpg/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :game
end

rpg/app/models/player.rb
class Player < ApplicationRecord
  has_one :game
end

rpg/app/models/step.rb
class Step < ApplicationRecord
    has_one :choice, dependent: :destroy

end

rpg/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]
  before_action :verify_connected, only: %i[ show edit update destroy ]
  before_action :isConnected

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
    @player = Player.select("login").find(params[:id])
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html do
          redirect_to root_path
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to request.referrer, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    if session[:user_id] == @player.id
      @player.destroy
      respond_to do |format|
        format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    def isConnected
      if !session[:role] && !session[:user_id]
        @connected = false
      else
        @connected = true
      end
    end

    def verify_connected
      if !session[:role] && !session[:user_id]
        redirect_to "/"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
      @allowed = false
      if @player && @player.id == session[:user_id] && session[:role] == "player"
        @allowed = true
      end
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:login, :password)
    end
end

rpg/app/helpers/answers_helper.rb
module AnswersHelper
end

rpg/app/helpers/gms_helper.rb
module GmsHelper
end

rpg/app/helpers/home_helper.rb
module HomeHelper
end

rpg/app/helpers/images_helper.rb
module ImagesHelper
end

rpg/app/helpers/loots_helper.rb
module LootsHelper
end

rpg/app/helpers/players_helper.rb
module PlayersHelper
end

rpg/app/helpers/steps_helper.rb
module StepsHelper
end

rpg/app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rpg/app/views/players/_player.html.erb
<%= render :partial => 'shared/disconnect' %>
<div id="<%= dom_id player %>">
  <p>
    <strong>Login:</strong>
    <%= player.login %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= player.password %>
  </p>

</div>

rpg/app/views/players/edit.html.erb
<%= render :partial => 'shared/disconnect' %>
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

rpg/app/views/players/index.html.erb
<%= render :partial => 'shared/disconnect' %>
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <p>Login: <%= player.login %></p>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

rpg/app/views/players/new.html.erb
<%= render :partial => 'shared/disconnect' %>
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

rpg/app/views/players/show.html.erb
<%= render :partial => 'shared/disconnect' %>
<p style="color: green"><%= notice %></p>


<p>Login: <%= @player.login %></p>

<div>
  <% if @allowed %>
    <%= link_to "Edit this player", edit_player_path(@player) %> |
  <% end %>
  <%= link_to "Back to players", players_path %>

  <% if @allowed %>
    <%= button_to "Destroy this player", @player, method: :delete %>
  <% end %>
</div>