rpg/config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :chapters
  resources :loots
  resources :game_players
  resources :players
  resources :gms
  get '/', to: "home#index"
  get '/home/gm', to: "home#loggm"
  get '/home/player', to: "home#logplayer"

  resources :messages
  resources :games
  resources :channels
  resources :home
  root "home#index"
  post '/home/logingm', to: "home#logingm"
  post '/home/loginplayer', to: "home#loginplayer"
  post '/home/disconnect', to: "home#disconnect"

  resources :choices do
    resources :answers
  end
  resources :steps
  resources :creatures
  get '/games', to: "games#index"
  post '/games/firstjoin/:game_id', to: "games#playerJoinGame"
  get '/games/viewAll/:entity/:id', to: "games#getMyGames"

  get '/games/character/new/:game_id', to: "characters#new"
  post '/games/character/new/:game_id', to: "characters#create"

  post '/game_players/leave/:game_id', to: "game_players#playerLeaveGame"

  get '/games/character/:character_id/setAttribute', to: "attributes#setAttributes"
  patch '/games/character/:character_id/saveAttributes', to: "attributes#saveAttributes"

  get '/games/:game_id/character/:character_id/:current_step', to: "games#playGame"

  get '/games/:game_id/character/:character_id/:current_step/loot/:loot_id', to: "games#earnLoot"

  get '/games/:game_id/character/:character_id/:current_step/wear/:loot_id', to: "games#addEquipment"

  get '/games/:game_id/character/:character_id/:current_step/fight/turn/:turn', to: "games#fight"

  patch '/games/:game_id/character/:character_id/:current_step', to: "attributes#saveAttributesXp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

rpg/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
end

rpg/app/models/channel.rb
class Channel < ApplicationRecord
    has_one :game
end

rpg/app/models/chapter.rb
class Chapter < ApplicationRecord
    has_many :steps, dependent: :destroy

end

rpg/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

rpg/app/models/choice.rb
class Choice < ApplicationRecord
    has_many :answers, dependent: :destroy

    validates :step_id, presence: true
    validates :description, presence: true, length: { minimum: 10 }

end

rpg/app/models/creature.rb
class Creature < ApplicationRecord
    validates :loot_id, presence: true
    validates :strength, presence: true
    validates :life, presence: true
    validates :image, presence: false
    validates :given_exp, presence: true
    

end

rpg/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :channel,
             :class_name => "Channel",
             :foreign_key => 'channel_id'
  has_many :messages, dependent: :destroy
  has_many :players
  has_many :game_players, dependent: :destroy
  has_many :characters, dependent: :destroy
  belongs_to :gm,
             dependent: :destroy,
             :class_name => "Gm",
             :foreign_key => 'gm_id'

 validates :name, presence: true
 validates :description, presence: true, length: { minimum: 10 }
 validates :chapter_id, presence: true
end

rpg/app/models/game_player.rb
class GamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

rpg/app/models/gm.rb
class Gm < ApplicationRecord
    has_one :game
end

rpg/app/models/image.rb
class Image < ApplicationRecord
end

rpg/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :player
  belongs_to :character
  belongs_to :game
end

rpg/app/models/loot.rb
class Loot < ApplicationRecord
end

rpg/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :game
end

rpg/app/models/player.rb
class Player < ApplicationRecord
  has_one :game
end

rpg/app/models/step.rb
class Step < ApplicationRecord
    has_one :choice, dependent: :destroy

end

rpg/app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :isConnected
  def index
    @choices = Choice.all
  end

  def show
    @choice=Choice.find(params[:id])
  end

  def new
    @choice = Choice.new
    @choice.answers.build
  end

 

  def create
    @choice = Choice.new(choice_params)

    if @choice.save
      redirect_to request.referrer
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @choice = Choice.find(params[:id])
  end

  def update
    @choice = Choice.find(params[:id])

    if @choice.update(choice_params)
      redirect_to request.referrer
    else
      render :edit, status: :unprocessable_entity
    end

  end

  def destroy
    @choice = Choice.find(params[:id])
    @choice.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def isConnected
      if !session[:role] && !session[:user_id]
        @connected = false
      else
        @connected = true
      end
    end

    def choice_params
      params.require(:choice).permit(:description, :step)
    end
end

rpg/app/helpers/answers_helper.rb
module AnswersHelper
end

rpg/app/helpers/choices_helper.rb
module ChoicesHelper
end

rpg/app/helpers/gms_helper.rb
module GmsHelper
end

rpg/app/helpers/home_helper.rb
module HomeHelper
end

rpg/app/helpers/images_helper.rb
module ImagesHelper
end

rpg/app/helpers/loots_helper.rb
module LootsHelper
end

rpg/app/helpers/steps_helper.rb
module StepsHelper
end

rpg/app/views/choices/_choice.html.erb
<p style="font-size: 1.3em">  <%= choice.description %></p>
<%= render choice.answers%>

rpg/app/views/choices/_editChoice.html.erb
<%= render "choices/form", choice: choice %>
<% choice.answers.each do |answer|%>
<%= render "/answers/answertoedit", answer: answer %>
<% end %>


<div><%= link_to "Edit Choice", edit_choice_path(choice) %></div>
<div><%= link_to "Destroy Choice", choice_path(choice), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>
<div><%= link_to "All Choices", choices_path%></div>

rpg/app/views/choices/_form.html.erb
<%= form_with model: choice do |form| %>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% choice.errors.full_messages_for(:description).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>
    </div>

  <div>
    <%= form.label :step_id %><br>
    <%= form.number_field :step_id %>
    <% choice.errors.full_messages_for(:step_id).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%if choice.id %>
 

<% end%>

rpg/app/views/choices/edit.html.erb
<h1>Edit Choice</h1>

<%= render "form", choice: @choice %>
<% @choice.answers.each do |answer|%>
<%= render "/answers/answertoedit", answer: answer %>
<% end %>

<%= render "/answers/form" %>

rpg/app/views/choices/index.html.erb
<h1>Choix</h1>

<%= link_to "New Choice", new_choice_path %>

<ul style="list-style: none;">
  <% @choices.each do |choice| %>
    <li>
      <%= choice.step_id %> ) <a href="<%= choice_path(choice) %>">  <%= choice.description %>  </a>
      => <%= link_to "Destroy Choice", choice_path(choice), data: {
                    turbo_method: :delete,
                  } %>
    </li>
  <% end %>
</ul>

rpg/app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render "form", choice: @choice %>

rpg/app/views/choices/newAnswer.html.erb
<h2>Add an Answer:</h2> 


 <%= form_with model: [ @choice, choice_url.answers.build ] do |form| %> 
   <p> 
     <%= form.label :description %><br> 
     <%= form.text_field :description %> 
   </p> 
   <p> 
     <%= form.label :next %><br> 
     <%= form.number_field :next %> 
   </p> 
    <p> 
     <%= form.label :exp %><br> 
     <%= form.number_field :exp %> 
   </p>
   <p> 
     <%= form.label :choice %><br> 
     <%= form.number_field :choice %> 
   </p> 
   <p> 
     <%= form.submit "valider" %> 
   </p> 
 <% end %>

rpg/app/views/choices/show.html.erb
<%= render @choice%>

<div><%= link_to "Edit Choice", edit_choice_path(@choice) %></div>
<div><%= link_to "Destroy Choice", choice_path(@choice), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>
<div><%= link_to "All Choices", choices_path%></div>