rpg/config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :chapters
  resources :loots
  resources :game_players
  resources :players
  resources :gms
  get '/', to: "home#index"
  get '/home/gm', to: "home#loggm"
  get '/home/player', to: "home#logplayer"

  resources :messages
  resources :games
  resources :channels
  resources :home
  root "home#index"
  post '/home/logingm', to: "home#logingm"
  post '/home/loginplayer', to: "home#loginplayer"
  post '/home/disconnect', to: "home#disconnect"

  resources :choices do
    resources :answers
  end
  resources :steps
  resources :creatures
  get '/games', to: "games#index"
  post '/games/firstjoin/:game_id', to: "games#playerJoinGame"
  get '/games/viewAll/:entity/:id', to: "games#getMyGames"

  get '/games/character/new/:game_id', to: "characters#new"
  post '/games/character/new/:game_id', to: "characters#create"

  post '/game_players/leave/:game_id', to: "game_players#playerLeaveGame"

  get '/games/character/:character_id/setAttribute', to: "attributes#setAttributes"
  patch '/games/character/:character_id/saveAttributes', to: "attributes#saveAttributes"

  get '/games/:game_id/character/:character_id/:current_step', to: "games#playGame"

  get '/games/:game_id/character/:character_id/:current_step/loot/:loot_id', to: "games#earnLoot"

  get '/games/:game_id/character/:character_id/:current_step/wear/:loot_id', to: "games#addEquipment"

  get '/games/:game_id/character/:character_id/:current_step/fight/turn/:turn', to: "games#fight"

  patch '/games/:game_id/character/:character_id/:current_step', to: "attributes#saveAttributesXp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

rpg/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
end

rpg/app/models/channel.rb
class Channel < ApplicationRecord
    has_one :game
end

rpg/app/models/chapter.rb
class Chapter < ApplicationRecord
    has_many :steps, dependent: :destroy

end

rpg/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

rpg/app/models/choice.rb
class Choice < ApplicationRecord
    has_many :answers, dependent: :destroy

    validates :step_id, presence: true
    validates :description, presence: true, length: { minimum: 10 }

end

rpg/app/models/creature.rb
class Creature < ApplicationRecord
    validates :loot_id, presence: true
    validates :strength, presence: true
    validates :life, presence: true
    validates :image, presence: false
    validates :given_exp, presence: true
    

end

rpg/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :channel,
             :class_name => "Channel",
             :foreign_key => 'channel_id'
  has_many :messages, dependent: :destroy
  has_many :players
  has_many :game_players, dependent: :destroy
  has_many :characters, dependent: :destroy
  belongs_to :gm,
             dependent: :destroy,
             :class_name => "Gm",
             :foreign_key => 'gm_id'

 validates :name, presence: true
 validates :description, presence: true, length: { minimum: 10 }
 validates :chapter_id, presence: true
end

rpg/app/models/game_player.rb
class GamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

rpg/app/models/gm.rb
class Gm < ApplicationRecord
    has_one :game
end

rpg/app/models/image.rb
class Image < ApplicationRecord
end

rpg/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :player
  belongs_to :character
  belongs_to :game
end

rpg/app/models/loot.rb
class Loot < ApplicationRecord
end

rpg/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :game
end

rpg/app/models/player.rb
class Player < ApplicationRecord
  has_one :game
end

rpg/app/models/step.rb
class Step < ApplicationRecord
    has_one :choice, dependent: :destroy

end

rpg/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]
  before_action :get_role
  before_action :verify_connected
  before_action :isConnected

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @gameId = params[:game_id]
    @origin = "new"
    @character = Character.new
    @player = Player.find(session[:user_id])
    @character.name = @player.login
  end

  # GET /characters/1/edit
  def edit
    @origin = "edit"
  end

  # POST /characters or /characters.json
  def create

    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        @character = Character.where(character_params).first
        @gamePlayer = GamePlayer.where(:game_id => character_params[:game_id], :player_id => session[:user_id])
        @gamePlayer.update(:character_id => @character.id)
        url = '/games/character/' + @character.id.to_s + '/setAttribute'
        format.html { redirect_to url, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_role
      @image_type = "player"
      if session[:role]
        @role = session[:role]
      else
        @role = "none"
      end
    end

    def isConnected
      if !session[:role] && !session[:user_id]
        @connected = false
      else
        @connected = true
      end
    end

    def verify_connected
      if !session[:role] && !session[:user_id]
        redirect_to "/"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :total_life, :life, :total_strength, :strength, :experience, :gold,
                                        :avatar, :game_id, :step_id, :chapter_id)
    end
end

rpg/app/helpers/answers_helper.rb
module AnswersHelper
end

rpg/app/helpers/characters_helper.rb
module CharactersHelper
end

rpg/app/helpers/gms_helper.rb
module GmsHelper
end

rpg/app/helpers/home_helper.rb
module HomeHelper
end

rpg/app/helpers/images_helper.rb
module ImagesHelper
end

rpg/app/helpers/loots_helper.rb
module LootsHelper
end

rpg/app/helpers/steps_helper.rb
module StepsHelper
end

rpg/app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <p>
    <strong>Name:</strong>
    <%= character.name %>
  </p>

  <p>
    <strong>Total life:</strong>
    <%= character.total_life %>
  </p>

  <p>
    <strong>Life:</strong>
    <%= character.life %>
  </p>

  <p>
    <strong>Total strength:</strong>
    <%= character.total_strength %>
  </p>

  <p>
    <strong>Strength:</strong>
    <%= character.strength %>
  </p>

  <p>
    <strong>Experience:</strong>
    <%= character.experience %>
  </p>

  <p>
    <strong>Gold:</strong>
    <%= character.gold %>
  </p>

  <p>
    <strong>Avatar:</strong>
    <%= character.avatar %>
  </p>

  <p>
    <strong>Step:</strong>
    <%= character.step_id %>
  </p>

  <p>
    <strong>Chapter:</strong>
    <%= character.chapter_id %>
  </p>

</div>

rpg/app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="select-sim" id="select-color">
    <div class="options">
      <%= form.collection_radio_buttons( :avatar , Image.where(["image_type = ?", @image_type]), :path, :name) do |b| %>
        <li> <%=b.label { b.radio_button + image_tag(b.object.path) }%></li>

      <%end%>
    </div>
  </div>

  <% if @role == "gm" %>
    <div>
      <%= form.label :total_life, style: "display: block" %>
      <%= form.number_field :total_life %>
    </div>

    <div>
      <%= form.label :life, style: "display: block" %>
      <%= form.number_field :life %>
    </div>

    <div>
      <%= form.label :total_strength, style: "display: block" %>
      <%= form.text_field :total_strength %>
    </div>

    <div>
      <%= form.label :strength, style: "display: block" %>
      <%= form.number_field :strength %>
    </div>

    <div>
      <%= form.label :experience, style: "display: block" %>
      <%= form.number_field :experience %>
    </div>

    <div>
      <%= form.label :gold, style: "display: block" %>
      <%= form.number_field :gold %>
    </div>



    <div>
      <%= form.label :step_id, style: "display: block" %>
      <%= form.text_field :step_id %>
    </div>

    <div>
      <%= form.label :chapter_id, style: "display: block" %>
      <%= form.text_field :chapter_id %>
    </div>

  <% end %>
  <div>
    <%= form.label :game_id, style: "display: none" %>
    <%= form.text_field :game_id, value: @gameId, style: "display: none" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

rpg/app/views/characters/edit.html.erb
<%= render :partial => 'shared/disconnect' %>
<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

rpg/app/views/characters/index.html.erb
<%= render :partial => 'shared/disconnect' %>
<p style="color: green"><%= notice %></p>

<h1>Characters</h1>

<div id="characters">
  <% @characters.each do |character| %>
    <%= render character %>
    <p>
      <%= link_to "Show this character", character %>
    </p>
  <% end %>
</div>

<%= link_to "New character", new_character_path %>

rpg/app/views/characters/new.html.erb
<%= render :partial => 'shared/disconnect' %>
<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

rpg/app/views/characters/show.html.erb
<%= render :partial => 'shared/disconnect' %>
<p style="color: green"><%= notice %></p>

<%= render @character %>

<div>
  <%= link_to "Edit this character", edit_character_path(@character) %> |
  <%= link_to "Back to characters", characters_path %>

  <%= button_to "Destroy this character", @character, method: :delete %>
</div>