rpg/config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :chapters
  resources :loots
  resources :game_players
  resources :players
  resources :gms
  get '/', to: "home#index"
  get '/home/gm', to: "home#loggm"
  get '/home/player', to: "home#logplayer"

  resources :messages
  resources :games
  resources :channels
  resources :home
  root "home#index"
  post '/home/logingm', to: "home#logingm"
  post '/home/loginplayer', to: "home#loginplayer"
  post '/home/disconnect', to: "home#disconnect"

  resources :choices do
    resources :answers
  end
  resources :steps
  resources :creatures
  get '/games', to: "games#index"
  post '/games/firstjoin/:game_id', to: "games#playerJoinGame"
  get '/games/viewAll/:entity/:id', to: "games#getMyGames"

  get '/games/character/new/:game_id', to: "characters#new"
  post '/games/character/new/:game_id', to: "characters#create"

  post '/game_players/leave/:game_id', to: "game_players#playerLeaveGame"

  get '/games/character/:character_id/setAttribute', to: "attributes#setAttributes"
  patch '/games/character/:character_id/saveAttributes', to: "attributes#saveAttributes"

  get '/games/:game_id/character/:character_id/:current_step', to: "games#playGame"

  get '/games/:game_id/character/:character_id/:current_step/loot/:loot_id', to: "games#earnLoot"

  get '/games/:game_id/character/:character_id/:current_step/wear/:loot_id', to: "games#addEquipment"

  get '/games/:game_id/character/:character_id/:current_step/fight/turn/:turn', to: "games#fight"

  patch '/games/:game_id/character/:character_id/:current_step', to: "attributes#saveAttributesXp"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

rpg/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
end

rpg/app/models/channel.rb
class Channel < ApplicationRecord
    has_one :game
end

rpg/app/models/chapter.rb
class Chapter < ApplicationRecord
    has_many :steps, dependent: :destroy

end

rpg/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

rpg/app/models/choice.rb
class Choice < ApplicationRecord
    has_many :answers, dependent: :destroy

    validates :step_id, presence: true
    validates :description, presence: true, length: { minimum: 10 }

end

rpg/app/models/creature.rb
class Creature < ApplicationRecord
    validates :loot_id, presence: true
    validates :strength, presence: true
    validates :life, presence: true
    validates :image, presence: false
    validates :given_exp, presence: true
    

end

rpg/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :channel,
             :class_name => "Channel",
             :foreign_key => 'channel_id'
  has_many :messages, dependent: :destroy
  has_many :players
  has_many :game_players, dependent: :destroy
  has_many :characters, dependent: :destroy
  belongs_to :gm,
             dependent: :destroy,
             :class_name => "Gm",
             :foreign_key => 'gm_id'

 validates :name, presence: true
 validates :description, presence: true, length: { minimum: 10 }
 validates :chapter_id, presence: true
end

rpg/app/models/game_player.rb
class GamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

rpg/app/models/gm.rb
class Gm < ApplicationRecord
    has_one :game
end

rpg/app/models/image.rb
class Image < ApplicationRecord
end

rpg/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :player
  belongs_to :character
  belongs_to :game
end

rpg/app/models/loot.rb
class Loot < ApplicationRecord
end

rpg/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :game
end

rpg/app/models/player.rb
class Player < ApplicationRecord
  has_one :game
end

rpg/app/models/step.rb
class Step < ApplicationRecord
    has_one :choice, dependent: :destroy

end

rpg/app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
    before_action :isConnected
    def index
      @creatures = Creature.all
      @images= Image.all
    end
  
    def show
      @creature=Creature.find(params[:id])
    end
  
    def new
      @creature = Creature.new
      @image_type = "creature"
    end

    def create
      @creature = Creature.new(creature_params)
  
      if @creature.save
        redirect_to creature_path(@creature.id)
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @creature = Creature.find(params[:id])
      @image_type = "creature"

    end
  
    def update
      @creature = Creature.find(params[:id])
  
      if @creature.update(creature_params)
        redirect_to request.referrer
      else
        render :edit, status: :unprocessable_entity
      end
  
    end
  
    def destroy
      @creature = Creature.find(params[:id])
      @creature.destroy
      puts creatures_url
      puts "tchao"
  
      redirect_to creatures_url, status: :see_other
    end
  
  
    private

      def isConnected
        if !session[:role] && !session[:user_id]
          @connected = false
        else
          @connected = true
        end
      end

      def creature_params
        params.require(:creature).permit(:loot_id, :strength, :life, :image, :given_exp, :description, :name)
      end
  end
  

rpg/app/helpers/answers_helper.rb
module AnswersHelper
end

rpg/app/helpers/creatures_helper.rb
module CreaturesHelper
end

rpg/app/helpers/gms_helper.rb
module GmsHelper
end

rpg/app/helpers/home_helper.rb
module HomeHelper
end

rpg/app/helpers/images_helper.rb
module ImagesHelper
end

rpg/app/helpers/loots_helper.rb
module LootsHelper
end

rpg/app/helpers/steps_helper.rb
module StepsHelper
end

rpg/app/views/creatures/_creature.html.erb
     <div>         <%= image_tag creature.image %>  </div>
     <div>         <%= creature.description %> </div>

rpg/app/views/creatures/_creaturetoedit.erb
<%= render creature %>
<div>    loot_id : <%= creature.loot_id %>  </div>
<div>    strength : <%= creature.strength %>  </div>
<div>    life : <%= creature.life %>  </div>
<div>    given_exp : <%= creature.given_exp %>  </div>



<div><%= link_to "Edit creature", edit_creature_path(creature) %></div>
<div><%= link_to "Destroy creature", creature_path(creature), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>
<div><%= link_to "All creatures", creatures_path%></div>

rpg/app/views/creatures/_form.html.erb
<%= form_with model: creature do |form| %>
<% image_type="creature"%>

  <div>

     <strong><%= form.label :name %><br></strong>
   <%= form.text_field :name %>
    <% creature.errors.full_messages_for(:name).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
  

  <div>
    <%= form.label :loot_id %><br>
    <%= form.number_field :loot_id %>
    <% creature.errors.full_messages_for(:loot_id).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
  <div>
    <%= form.label :strength %><br>
    <%= form.number_field :strength %>
    <% creature.errors.full_messages_for(:strength).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
  <div>

    <%= form.label :life %><br>
    <%= form.number_field :life %>
    <% creature.errors.full_messages_for(:life).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
  <div>

    <%= form.label :given_exp %><br>
    <%= form.number_field :given_exp %>
    <% creature.errors.full_messages_for(:given_exp).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
  <div class="select-sim" id="select-color">
    <div class="options">
      <%= form.collection_radio_buttons( :image , Image.where(["image_type = ?", image_type]), :path, :name) do |b| %>
        <li> <%=b.label { b.radio_button + image_tag(b.object.path) }%></li>
        
        <%end%>
    </div>
  </div>

   



 
  
  <div>

    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% creature.errors.full_messages_for(:description).each do |message| %>
    <div style="color:red"><%= message %></div>
    <% end %>

  </div>
       
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%if creature.id %>
 

<% end%>

rpg/app/views/creatures/_show.html.erb
<p>  <%= creature.id %></p>
  
     <div>         <%= image_tag creature.image %> , </div>
     <div>    loot_id : <%= creature.loot_id %> , </div>
     <div>    strength : <%= creature.strength %> , </div>
     <div>    life : <%= creature.life %> , </div>
     <div>    description : <%= creature.description %> </div>
     <div>    given_exp : <%= creature.given_exp %> , </div>

<div><%= link_to "Edit creature", edit_creature_path(creature) %></div>
<div><%= link_to "Destroy creature", creature_path(creature), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>
<div><%= link_to "All creatures", creatures_path%></div>

rpg/app/views/creatures/edit.html.erb
<h1>Edit creature</h1>

<%= render "form", creature: @creature %>


<div><%= link_to "Destroy creature", creature_path(@creature), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>

rpg/app/views/creatures/index.html.erb
<h1>welcome on creatures manager</h1>

<%= link_to "New creature", new_creature_path %>
<ul style="list-style: none;">
  <% @creatures.each do |creature| %>
    <li>
      <a href="<%= creature_path(creature) %>">
      
      <%= image_tag creature.image %>
      loot_id : <%= creature.loot_id %> , 
      strength : <%= creature.strength %> , 
      life : <%= creature.life %> , 
      description : <%= creature.description %> 
      given_exp : <%= creature.given_exp %> , 
      </a>
    <p><%= link_to "Destroy creature", creature_path(creature), data: {
                    turbo_method: :delete,
                  } %> </p>
    </li>
  <% end %>
</ul>

rpg/app/views/creatures/new.html.erb
<h1>New creature</h1>

<%= render "form", creature: @creature %>

rpg/app/views/creatures/show.html.erb
<%= render "creature", creature: @creature %>

<div><%= link_to "Edit creature", edit_creature_path(@creature) %></div>
<div><%= link_to "Destroy creature", creature_path(@creature), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></div>
<div><%= link_to "All creatures", creatures_path%></div>